# Generated by Django 5.1.3 on 2025-01-26 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App1", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="apartmentId",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="App1.appartment",
            ),
        ),
    ]
