# Generated by Django 5.1.3 on 2025-01-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App1", "0002_request_apartmentid"),
    ]

    operations = [
        migrations.AddField(
            model_name="seller",
            name="commission",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
