# Generated by Django 5.1.3 on 2025-01-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App1", "0003_seller_commission"),
    ]

    operations = [
        migrations.AddField(
            model_name="seller",
            name="total_commission",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
